### ISSUE TITLE
Deprecate project

### ISSUE THREAD

**Issue by blurayne** [Aaronepower/eve#1]
Common error in docker: not using 'envsubst'

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Not sure what that has to do with this. I'll decide what to do with my project.

**Comment by blurayne** [comment]
Well, you don't need to reinvent the wheel since there are already solutions:
https://linux.die.net/man/1/envsubst

And since envsubst is way too simple we also have renvsubst respecting quotes:
https://crates.io/crates/renvsubst

Or the further parameter substitution:
https://godoc.org/github.com/a8m/envsubst

And it may be commonly be seen in CI usage or with docker execution – but using `sed` is just prone to errors and unnecessary.

**Comment by XAMPPRocky** [comment]
I'll spend my time how I choose thank you.
